[package]
name = "sled"
version = "0.15.6"
authors = ["Tyler Neely <t@jujit.su>"]
description = "a flash-sympathetic persistent lock-free B+ tree"
license = "MIT/Apache-2.0"
homepage = "https://github.com/spacejam/sled"
repository = "https://github.com/spacejam/sled"
keywords = ["database", "embedded", "concurrent", "persistent", "lock-free"]
documentation = "https://docs.rs/sled/"
readme = "../../README.md"

[features]
default = []
lock_free_delays = ["pagecache/lock_free_delays"]
failpoints = ["pagecache/failpoints"]
check_snapshot_integrity = []
no_logs = ["log/max_level_off", "pagecache/no_logs"]
rayon = ["pagecache/rayon"]
zstd = ["pagecache/zstd"]

[profile.release]
debug = 2

[dependencies.log]
version = "0.4"

[dependencies]
crossbeam-epoch = "0.4"
bincode = "0.9"
serde = "1.0"
serde_derive = "1.0"
clippy = {version = "0.0", optional = true}
pagecache = { path = "../pagecache", version = "0.2.4" }
