[package]
name = "sled"
version = "0.16.2"
authors = ["Tyler Neely <t@jujit.su>"]
description = "a flash-sympathetic persistent lock-free B+ tree"
license = "MIT/Apache-2.0"
homepage = "https://github.com/spacejam/sled"
repository = "https://github.com/spacejam/sled"
keywords = ["database", "embedded", "concurrent", "persistent", "lock-free"]
documentation = "https://docs.rs/sled/"
readme = "../../README.md"

[features]
default = []
lock_free_delays = ["pagecache/lock_free_delays"]
failpoints = ["pagecache/failpoints"]
check_snapshot_integrity = []
no_logs = ["log/max_level_off", "pagecache/no_logs"]
no_metrics = ["pagecache/no_metrics"]
zstd = ["pagecache/zstd"]
nightly = ["pagecache/nightly"]
no_inline = ["pagecache/no_inline"]

[dependencies.log]
version = "0.4"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
pagecache = { path = "../pagecache", version = "0.7.0" }
